from .home import home_view
from .settings import settings_view
from .shop import shop_view
from .product import product_view
from .cart import cart_view
from .orders import orders_view
from .components import footer_bar
from .regist import regist_view
from .login import login_view
from .admin import admin_view
